// prisma/seed.ts
// Seeds the database with 30 diverse job listings including Indian companies.
// Run: npx ts-node --compiler-options '{"module":"CommonJS"}' prisma/seed.ts
// Or:  npx prisma db seed

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const rawJobs = [
  // ── TECH ────────────────────────────────────────────────────────────────────
  {
    title: "Senior Full Stack Engineer",
    company: "Nexus Labs",
    companySlug: "nexus-labs",
    logo: "https://ui-avatars.com/api/?name=Nexus+Labs&background=1e3a5f&color=38bdf8&bold=true",
    location: "San Francisco, CA",
    city: "San Francisco",
    salary: "$140,000 – $180,000",
    salaryMin: 140000,
    salaryMax: 180000,
    type: "full-time",
    description:
      "Join Nexus Labs to build scalable web applications serving millions of users. You'll work across our React/Node stack, mentor junior engineers, and shape technical direction for our core platform team.",
    requirements: [
      "5+ years experience with React and Node.js",
      "Strong TypeScript skills",
      "Experience with PostgreSQL and Redis",
      "Excellent communication and collaboration",
    ],
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "Redis"],
    category: "Tech",
    featured: true,
    experience: "senior",
    workMode: "hybrid",
    industry: "IT",
    noticePeriod: "1-month",
    companyRating: 4.7,
    applicantCount: 248,
  },
  {
    title: "Frontend Developer",
    company: "Nexus Labs",
    companySlug: "nexus-labs",
    logo: "https://ui-avatars.com/api/?name=Nexus+Labs&background=1e3a5f&color=38bdf8&bold=true",
    location: "San Francisco, CA",
    city: "San Francisco",
    salary: "$110,000 – $145,000",
    salaryMin: 110000,
    salaryMax: 145000,
    type: "full-time",
    description:
      "Build beautiful, performant interfaces for Nexus Labs' flagship product. You'll work with Next.js, Tailwind, and our design system to ship features weekly.",
    requirements: [
      "3+ years React/Next.js experience",
      "Strong CSS and responsive design",
      "Experience with accessibility standards",
      "Testing with Jest and Playwright",
    ],
    skills: ["React", "Next.js", "Tailwind CSS", "TypeScript", "Jest"],
    category: "Tech",
    featured: false,
    experience: "mid",
    workMode: "hybrid",
    industry: "IT",
    noticePeriod: "1-month",
    companyRating: 4.7,
    applicantCount: 184,
  },
  {
    title: "Machine Learning Engineer",
    company: "AI Horizon",
    companySlug: "ai-horizon",
    logo: "https://ui-avatars.com/api/?name=AI+Horizon&background=1e3a5f&color=38bdf8&bold=true",
    location: "Seattle, WA",
    city: "Seattle",
    salary: "$160,000 – $210,000",
    salaryMin: 160000,
    salaryMax: 210000,
    type: "full-time",
    description:
      "Build and deploy ML models for our recommendation engine. You'll work with PyTorch, feature stores, and real-time inference pipelines serving 50M+ users daily.",
    requirements: [
      "MS/PhD in CS or equivalent experience",
      "Production ML deployment experience",
      "Python, PyTorch or TensorFlow",
      "Experience with MLOps tools",
    ],
    skills: ["Python", "PyTorch", "MLOps", "Kubernetes", "Spark"],
    category: "Tech",
    featured: true,
    experience: "senior",
    workMode: "onsite",
    industry: "IT",
    noticePeriod: "2-months",
    companyRating: 4.8,
    applicantCount: 312,
  },
  {
    title: "Remote DevOps Engineer",
    company: "CloudForge",
    companySlug: "cloudforge",
    logo: "https://ui-avatars.com/api/?name=CloudForge&background=1e3a5f&color=38bdf8&bold=true",
    location: "Remote (US)",
    city: "Remote",
    salary: "$130,000 – $165,000",
    salaryMin: 130000,
    salaryMax: 165000,
    type: "remote",
    description:
      "CloudForge is a fully remote company building infrastructure tools. You'll manage Kubernetes clusters, CI/CD pipelines, and observability across AWS and GCP.",
    requirements: [
      "4+ years DevOps/SRE experience",
      "Expertise in Kubernetes and Terraform",
      "Experience with AWS or GCP",
      "Strong scripting (Python or Go)",
    ],
    skills: ["Kubernetes", "Terraform", "AWS", "GCP", "Python", "Go"],
    category: "Tech",
    featured: true,
    experience: "senior",
    workMode: "remote",
    industry: "IT",
    noticePeriod: "1-month",
    companyRating: 4.5,
    applicantCount: 196,
  },
  {
    title: "Cybersecurity Analyst",
    company: "SecureNet",
    companySlug: "securenet",
    logo: "https://ui-avatars.com/api/?name=SecureNet&background=1e3a5f&color=38bdf8&bold=true",
    location: "Washington, DC",
    city: "Washington",
    salary: "$95,000 – $125,000",
    salaryMin: 95000,
    salaryMax: 125000,
    type: "full-time",
    description:
      "Monitor threats, conduct incident response, and implement security controls for enterprise clients. SOC experience required.",
    requirements: [
      "3+ years cybersecurity experience",
      "SIEM tools (Splunk, Sentinel)",
      "Security certifications (Security+, CISSP)",
      "Incident response experience",
    ],
    skills: ["Splunk", "SIEM", "Incident Response", "CISSP", "Penetration Testing"],
    category: "Tech",
    featured: false,
    experience: "mid",
    workMode: "onsite",
    industry: "IT",
    noticePeriod: "1-month",
    companyRating: 4.3,
    applicantCount: 142,
  },
  {
    title: "Data Engineer",
    company: "Nexus Labs",
    companySlug: "nexus-labs",
    logo: "https://ui-avatars.com/api/?name=Nexus+Labs&background=1e3a5f&color=38bdf8&bold=true",
    location: "San Francisco, CA",
    city: "San Francisco",
    salary: "$135,000 – $170,000",
    salaryMin: 135000,
    salaryMax: 170000,
    type: "full-time",
    description:
      "Design and maintain data pipelines using Spark, Airflow, and Snowflake. Enable analytics and ML teams with reliable, high-quality datasets.",
    requirements: [
      "3+ years data engineering",
      "SQL and Python expertise",
      "Experience with dbt or Airflow",
      "Cloud data warehouse (Snowflake/BigQuery)",
    ],
    skills: ["Spark", "Airflow", "Snowflake", "dbt", "SQL", "Python"],
    category: "Tech",
    featured: false,
    experience: "mid",
    workMode: "hybrid",
    industry: "IT",
    noticePeriod: "1-month",
    companyRating: 4.7,
    applicantCount: 167,
  },
  // ── INDIA TECH ───────────────────────────────────────────────────────────────
  {
    title: "Software Development Engineer II",
    company: "Zomato",
    companySlug: "zomato",
    logo: "https://ui-avatars.com/api/?name=Zomato&background=e23744&color=fff&bold=true",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    salary: "₹25 – ₹40 LPA",
    salaryMin: 2500000,
    salaryMax: 4000000,
    type: "full-time",
    description:
      "Work on high-scale backend systems processing 5M+ orders daily. You'll design microservices in Go, optimize database performance, and collaborate with product to build features for India's #1 food delivery platform.",
    requirements: [
      "3+ years backend development",
      "Strong in Go, Java, or Python",
      "Experience with distributed systems",
      "Familiarity with Kafka and Redis",
    ],
    skills: ["Go", "Java", "Kafka", "Redis", "MySQL", "Docker"],
    category: "Tech",
    featured: true,
    experience: "mid",
    workMode: "hybrid",
    industry: "E-Commerce",
    noticePeriod: "2-months",
    companyRating: 4.2,
    applicantCount: 534,
  },
  {
    title: "Senior Backend Engineer",
    company: "Flipkart",
    companySlug: "flipkart",
    logo: "https://ui-avatars.com/api/?name=Flipkart&background=2874f0&color=fff&bold=true",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    salary: "₹30 – ₹50 LPA",
    salaryMin: 3000000,
    salaryMax: 5000000,
    type: "full-time",
    description:
      "Build and scale the backend systems powering India's largest e-commerce platform. Work with a talented engineering team on problems at massive scale — serving 100M+ customers.",
    requirements: [
      "5+ years backend engineering",
      "Strong Java or Golang",
      "Experience with microservices architecture",
      "Proficiency in database design",
    ],
    skills: ["Java", "Spring Boot", "Microservices", "MongoDB", "Elasticsearch"],
    category: "Tech",
    featured: true,
    experience: "senior",
    workMode: "onsite",
    industry: "E-Commerce",
    noticePeriod: "2-months",
    companyRating: 4.1,
    applicantCount: 489,
  },
  {
    title: "Full Stack Developer",
    company: "Razorpay",
    companySlug: "razorpay",
    logo: "https://ui-avatars.com/api/?name=Razorpay&background=3395ff&color=fff&bold=true",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    salary: "₹20 – ₹32 LPA",
    salaryMin: 2000000,
    salaryMax: 3200000,
    type: "full-time",
    description:
      "Join Razorpay's product engineering team to build features for India's leading fintech platform. You'll own features end-to-end, from React frontend to Node.js backend.",
    requirements: [
      "3+ years full stack experience",
      "Proficiency in React and Node.js",
      "Understanding of payment systems",
      "Strong API design skills",
    ],
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    category: "Tech",
    featured: false,
    experience: "mid",
    workMode: "hybrid",
    industry: "Banking",
    noticePeriod: "1-month",
    companyRating: 4.4,
    applicantCount: 381,
  },
  {
    title: "Cloud Architect",
    company: "Infosys",
    companySlug: "infosys",
    logo: "https://ui-avatars.com/api/?name=Infosys&background=007cc3&color=fff&bold=true",
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    salary: "₹35 – ₹55 LPA",
    salaryMin: 3500000,
    salaryMax: 5500000,
    type: "full-time",
    description:
      "Lead cloud transformation projects for Fortune 500 clients. You'll architect multi-cloud solutions on AWS/Azure/GCP, define technical standards, and mentor a team of 15 engineers.",
    requirements: [
      "8+ years IT experience with 5 in cloud",
      "AWS/Azure/GCP professional certification",
      "Strong in Terraform and CloudFormation",
      "Excellent client communication",
    ],
    skills: ["AWS", "Azure", "GCP", "Terraform", "Kubernetes", "Architecture"],
    category: "Tech",
    featured: false,
    experience: "lead",
    workMode: "hybrid",
    industry: "Consulting",
    noticePeriod: "3-months",
    companyRating: 3.9,
    applicantCount: 213,
  },
  // ── DESIGN ───────────────────────────────────────────────────────────────────
  {
    title: "Product Designer",
    company: "Pixelcraft Studio",
    companySlug: "pixelcraft-studio",
    logo: "https://ui-avatars.com/api/?name=Pixelcraft&background=7c3aed&color=fff&bold=true",
    location: "New York, NY",
    city: "New York",
    salary: "$95,000 – $130,000",
    salaryMin: 95000,
    salaryMax: 130000,
    type: "full-time",
    description:
      "Own end-to-end design for our SaaS dashboard. You'll conduct user research, create high-fidelity prototypes, and collaborate closely with engineering to ship pixel-perfect features.",
    requirements: [
      "3+ years in product or UX design",
      "Proficiency in Figma",
      "Portfolio demonstrating SaaS work",
      "Understanding of design systems",
    ],
    skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Usability Testing"],
    category: "Design",
    featured: true,
    experience: "mid",
    workMode: "onsite",
    industry: "IT",
    noticePeriod: "1-month",
    companyRating: 4.6,
    applicantCount: 289,
  },
  {
    title: "UX Designer",
    company: "Swiggy",
    companySlug: "swiggy",
    logo: "https://ui-avatars.com/api/?name=Swiggy&background=fc8019&color=fff&bold=true",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    salary: "₹18 – ₹28 LPA",
    salaryMin: 1800000,
    salaryMax: 2800000,
    type: "full-time",
    description:
      "Design intuitive experiences for Swiggy's 80M+ active users. You'll work on the consumer app, partner app, and Swiggy Instamart — crafting flows that reduce friction and delight customers.",
    requirements: [
      "3+ years UX design experience",
      "Mobile-first design expertise",
      "Figma proficiency",
      "Data-informed design approach",
    ],
    skills: ["Figma", "Mobile UX", "Prototyping", "User Research", "Adobe XD"],
    category: "Design",
    featured: false,
    experience: "mid",
    workMode: "hybrid",
    industry: "E-Commerce",
    noticePeriod: "1-month",
    companyRating: 4.0,
    applicantCount: 274,
  },
  {
    title: "Brand Designer",
    company: "Vivid Agency",
    companySlug: "vivid-agency",
    logo: "https://ui-avatars.com/api/?name=Vivid&background=ec4899&color=fff&bold=true",
    location: "Los Angeles, CA",
    city: "Los Angeles",
    salary: "$70,000 – $90,000",
    salaryMin: 70000,
    salaryMax: 90000,
    type: "contract",
    description:
      "6-month contract to refresh brand identity for three major clients. You'll deliver logos, style guides, and marketing collateral that sets brands apart in competitive markets.",
    requirements: [
      "Strong portfolio in brand design",
      "Adobe Creative Suite expertise",
      "Experience with print and digital",
      "Ability to manage multiple clients",
    ],
    skills: ["Adobe Illustrator", "Photoshop", "Brand Strategy", "Typography"],
    category: "Design",
    featured: false,
    experience: "mid",
    workMode: "remote",
    industry: "Consulting",
    noticePeriod: "immediate",
    companyRating: 4.2,
    applicantCount: 156,
  },
  // ── MARKETING ────────────────────────────────────────────────────────────────
  {
    title: "Digital Marketing Manager",
    company: "GrowthHive",
    companySlug: "growthhive",
    logo: "https://ui-avatars.com/api/?name=GrowthHive&background=10b981&color=fff&bold=true",
    location: "Austin, TX",
    city: "Austin",
    salary: "$85,000 – $110,000",
    salaryMin: 85000,
    salaryMax: 110000,
    type: "full-time",
    description:
      "Lead our digital marketing strategy across SEO, paid media, and content. You'll manage a team of specialists and report directly to the VP of Marketing.",
    requirements: [
      "4+ years in digital marketing",
      "Experience with Google Ads and Meta Ads",
      "Strong analytics skills (GA4, Looker)",
      "B2B SaaS experience preferred",
    ],
    skills: ["Google Ads", "Meta Ads", "SEO", "GA4", "HubSpot", "Looker"],
    category: "Marketing",
    featured: true,
    experience: "senior",
    workMode: "hybrid",
    industry: "IT",
    noticePeriod: "1-month",
    companyRating: 4.3,
    applicantCount: 203,
  },
  {
    title: "Growth Marketing Lead",
    company: "CRED",
    companySlug: "cred",
    logo: "https://ui-avatars.com/api/?name=CRED&background=1a1a1a&color=fff&bold=true",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    salary: "₹20 – ₹35 LPA",
    salaryMin: 2000000,
    salaryMax: 3500000,
    type: "full-time",
    description:
      "Drive user acquisition, engagement, and retention for CRED's 10M+ premium member base. Own growth experiments across referral, content, and performance marketing channels.",
    requirements: [
      "4+ years growth marketing experience",
      "Strong data-driven mindset",
      "Experience with A/B testing",
      "Fintech or D2C background preferred",
    ],
    skills: ["Growth Hacking", "A/B Testing", "Analytics", "CRM", "Referral Programs"],
    category: "Marketing",
    featured: false,
    experience: "mid",
    workMode: "onsite",
    industry: "Banking",
    noticePeriod: "2-months",
    companyRating: 4.5,
    applicantCount: 298,
  },
  // ── FINANCE ──────────────────────────────────────────────────────────────────
  {
    title: "Financial Analyst",
    company: "Meridian Capital",
    companySlug: "meridian-capital",
    logo: "https://ui-avatars.com/api/?name=Meridian&background=0f766e&color=fff&bold=true",
    location: "Chicago, IL",
    city: "Chicago",
    salary: "$75,000 – $95,000",
    salaryMin: 75000,
    salaryMax: 95000,
    type: "full-time",
    description:
      "Support FP&A, budgeting, and investor reporting. Build financial models and partner with department leads on strategic planning for a mid-market PE-backed firm.",
    requirements: [
      "Bachelor's in Finance or Accounting",
      "2+ years in FP&A or investment banking",
      "Advanced Excel and financial modeling",
      "CPA or CFA progress preferred",
    ],
    skills: ["Financial Modeling", "Excel", "FP&A", "Budgeting", "PowerBI"],
    category: "Finance",
    featured: false,
    experience: "junior",
    workMode: "onsite",
    industry: "Banking",
    noticePeriod: "1-month",
    companyRating: 4.0,
    applicantCount: 178,
  },
  {
    title: "Investment Banking Associate",
    company: "Meridian Capital",
    companySlug: "meridian-capital",
    logo: "https://ui-avatars.com/api/?name=Meridian&background=0f766e&color=fff&bold=true",
    location: "New York, NY",
    city: "New York",
    salary: "$150,000 – $200,000",
    salaryMin: 150000,
    salaryMax: 200000,
    type: "full-time",
    description:
      "Join Meridian's M&A team working on middle-market transactions. Long hours but exceptional learning, mentorship, and bonus structure.",
    requirements: [
      "MBA from top program or 2+ years IB",
      "Strong financial modeling",
      "Excellent attention to detail",
      "Willingness to travel",
    ],
    skills: ["M&A", "Financial Modeling", "DCF", "LBO", "Pitchbooks"],
    category: "Finance",
    featured: true,
    experience: "mid",
    workMode: "onsite",
    industry: "Banking",
    noticePeriod: "1-month",
    companyRating: 4.0,
    applicantCount: 267,
  },
  {
    title: "Chartered Accountant",
    company: "Deloitte India",
    companySlug: "deloitte-india",
    logo: "https://ui-avatars.com/api/?name=Deloitte&background=86bc25&color=fff&bold=true",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    salary: "₹12 – ₹18 LPA",
    salaryMin: 1200000,
    salaryMax: 1800000,
    type: "full-time",
    description:
      "Join Deloitte India's audit practice as a Chartered Accountant. You'll lead statutory audits for listed companies, handle client relationships, and supervise a team of article assistants.",
    requirements: [
      "CA qualification (ICAI)",
      "2+ years post-qualification experience",
      "Experience in statutory audit",
      "Excellent client handling skills",
    ],
    skills: ["Audit", "Taxation", "Financial Reporting", "IFRS", "SAP"],
    category: "Finance",
    featured: false,
    experience: "junior",
    workMode: "hybrid",
    industry: "Consulting",
    noticePeriod: "3-months",
    companyRating: 4.2,
    applicantCount: 423,
  },
  // ── HEALTHCARE ───────────────────────────────────────────────────────────────
  {
    title: "Registered Nurse – ICU",
    company: "Summit Health",
    companySlug: "summit-health",
    logo: "https://ui-avatars.com/api/?name=Summit+Health&background=dc2626&color=fff&bold=true",
    location: "Boston, MA",
    city: "Boston",
    salary: "$72,000 – $88,000",
    salaryMin: 72000,
    salaryMax: 88000,
    type: "full-time",
    description:
      "Summit Health is hiring ICU Registered Nurses for our Level II trauma center. Competitive benefits, sign-on bonus, and continuing education support included.",
    requirements: [
      "Active RN license in Massachusetts",
      "BSN preferred",
      "1+ year ICU experience",
      "BLS and ACLS certification",
    ],
    skills: ["ICU Care", "BLS", "ACLS", "Patient Assessment", "EHR (Epic)"],
    category: "Healthcare",
    featured: false,
    experience: "junior",
    workMode: "onsite",
    industry: "Healthcare",
    noticePeriod: "15-days",
    companyRating: 4.4,
    applicantCount: 92,
  },
  {
    title: "Healthcare Data Analyst",
    company: "Apollo Hospitals",
    companySlug: "apollo-hospitals",
    logo: "https://ui-avatars.com/api/?name=Apollo&background=003366&color=fff&bold=true",
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    salary: "₹8 – ₹14 LPA",
    salaryMin: 800000,
    salaryMax: 1400000,
    type: "full-time",
    description:
      "Analyze patient outcomes, operational efficiency, and revenue cycle data for one of India's leading hospital networks. Build dashboards and reports for C-suite decision-making.",
    requirements: [
      "2+ years data analytics experience",
      "SQL and Python proficiency",
      "Healthcare domain knowledge preferred",
      "Experience with Tableau or Power BI",
    ],
    skills: ["SQL", "Python", "Tableau", "Power BI", "Healthcare Analytics"],
    category: "Healthcare",
    featured: false,
    experience: "junior",
    workMode: "hybrid",
    industry: "Healthcare",
    noticePeriod: "1-month",
    companyRating: 4.0,
    applicantCount: 187,
  },
  // ── EDUCATION ─────────────────────────────────────────────────────────────────
  {
    title: "Curriculum Developer – Tech",
    company: "upGrad",
    companySlug: "upgrad",
    logo: "https://ui-avatars.com/api/?name=upGrad&background=ff5f1f&color=fff&bold=true",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    salary: "₹10 – ₹16 LPA",
    salaryMin: 1000000,
    salaryMax: 1600000,
    type: "full-time",
    description:
      "Design and develop cutting-edge tech curriculum for upGrad's online degree and certification programs. Work with industry experts to create hands-on, job-ready learning experiences for 50L+ learners.",
    requirements: [
      "3+ years software development or data science",
      "Passion for teaching and content creation",
      "Experience with LMS platforms",
      "Strong written communication",
    ],
    skills: ["Curriculum Design", "Python", "Data Science", "Instructional Design", "E-Learning"],
    category: "Tech",
    featured: false,
    experience: "mid",
    workMode: "hybrid",
    industry: "Education",
    noticePeriod: "1-month",
    companyRating: 3.9,
    applicantCount: 145,
  },
  // ── REMOTE ───────────────────────────────────────────────────────────────────
  {
    title: "Remote Software Engineer",
    company: "AI Horizon",
    companySlug: "ai-horizon",
    logo: "https://ui-avatars.com/api/?name=AI+Horizon&background=1e3a5f&color=38bdf8&bold=true",
    location: "Remote (US)",
    city: "Remote",
    salary: "$120,000 – $155,000",
    salaryMin: 120000,
    salaryMax: 155000,
    type: "remote",
    description:
      "Build backend services for our ML platform. Work async with a distributed team across US time zones. Strong async communication and self-direction required.",
    requirements: [
      "4+ years backend development",
      "Python or Go experience",
      "API design and microservices",
      "Comfort with remote collaboration",
    ],
    skills: ["Python", "Go", "REST APIs", "Microservices", "Docker"],
    category: "Remote",
    featured: true,
    experience: "mid",
    workMode: "remote",
    industry: "IT",
    noticePeriod: "15-days",
    companyRating: 4.8,
    applicantCount: 341,
  },
  {
    title: "Remote Customer Success Manager",
    company: "CloudForge",
    companySlug: "cloudforge",
    logo: "https://ui-avatars.com/api/?name=CloudForge&background=1e3a5f&color=38bdf8&bold=true",
    location: "Remote (Global)",
    city: "Remote",
    salary: "$80,000 – $100,000",
    salaryMin: 80000,
    salaryMax: 100000,
    type: "remote",
    description:
      "Own relationships with enterprise accounts, drive adoption, and reduce churn. You'll partner with sales and product on expansion opportunities across APAC and EMEA.",
    requirements: [
      "3+ years in B2B customer success",
      "Technical SaaS background",
      "Experience with Gainsight or similar",
      "Strong presentation skills",
    ],
    skills: ["Customer Success", "Gainsight", "CRM", "SaaS", "Account Management"],
    category: "Remote",
    featured: false,
    experience: "mid",
    workMode: "remote",
    industry: "IT",
    noticePeriod: "1-month",
    companyRating: 4.5,
    applicantCount: 128,
  },
  {
    title: "Remote Technical Writer",
    company: "CloudForge",
    companySlug: "cloudforge",
    logo: "https://ui-avatars.com/api/?name=CloudForge&background=1e3a5f&color=38bdf8&bold=true",
    location: "Remote (US)",
    city: "Remote",
    salary: "$70,000 – $90,000",
    salaryMin: 70000,
    salaryMax: 90000,
    type: "remote",
    description:
      "Document APIs, SDKs, and developer workflows. Work with engineering to keep docs accurate and developer-friendly. Own the developer documentation portal end-to-end.",
    requirements: [
      "3+ years technical writing",
      "API documentation experience",
      "Markdown and docs-as-code",
      "Developer background preferred",
    ],
    skills: ["Technical Writing", "Markdown", "OpenAPI", "Git", "Developer Docs"],
    category: "Remote",
    featured: false,
    experience: "mid",
    workMode: "remote",
    industry: "IT",
    noticePeriod: "1-month",
    companyRating: 4.5,
    applicantCount: 87,
  },
  {
    title: "Remote Graphic Designer",
    company: "Vivid Agency",
    companySlug: "vivid-agency",
    logo: "https://ui-avatars.com/api/?name=Vivid&background=ec4899&color=fff&bold=true",
    location: "Remote (Global)",
    city: "Remote",
    salary: "$45,000 – $60,000",
    salaryMin: 45000,
    salaryMax: 60000,
    type: "contract",
    description:
      "Create social graphics, ad creatives, and presentation decks for diverse global clients. Fast turnaround and creative flexibility required.",
    requirements: [
      "2+ years graphic design",
      "Adobe Illustrator and Photoshop",
      "Motion graphics a plus",
      "Portfolio required",
    ],
    skills: ["Adobe Illustrator", "Photoshop", "After Effects", "Canva"],
    category: "Remote",
    featured: false,
    experience: "junior",
    workMode: "remote",
    industry: "Consulting",
    noticePeriod: "immediate",
    companyRating: 4.2,
    applicantCount: 231,
  },
  // ── STARTUP ──────────────────────────────────────────────────────────────────
  {
    title: "Product Manager – Payments",
    company: "PhonePe",
    companySlug: "phonepe",
    logo: "https://ui-avatars.com/api/?name=PhonePe&background=5f259f&color=fff&bold=true",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    salary: "₹28 – ₹45 LPA",
    salaryMin: 2800000,
    salaryMax: 4500000,
    type: "full-time",
    description:
      "Define the product roadmap for PhonePe's UPI payments infrastructure serving 500M+ users. You'll work with engineering, design, and business teams to ship features that set the standard for India's digital payments ecosystem.",
    requirements: [
      "4+ years product management experience",
      "Understanding of payment systems/fintech",
      "Data-driven decision making",
      "Excellent stakeholder management",
    ],
    skills: ["Product Strategy", "UPI", "Fintech", "Agile", "SQL", "Roadmapping"],
    category: "Tech",
    featured: true,
    experience: "senior",
    workMode: "hybrid",
    industry: "Banking",
    noticePeriod: "2-months",
    companyRating: 4.3,
    applicantCount: 612,
  },
  {
    title: "Senior iOS Developer",
    company: "BYJU'S",
    companySlug: "byjus",
    logo: "https://ui-avatars.com/api/?name=BYJU&background=1877f2&color=fff&bold=true",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    salary: "₹22 – ₹38 LPA",
    salaryMin: 2200000,
    salaryMax: 3800000,
    type: "full-time",
    description:
      "Build engaging, high-performance iOS experiences for BYJU's learning app used by 150M+ students. Work on interactive content delivery, AR learning features, and offline-first architecture.",
    requirements: [
      "4+ years iOS development",
      "Strong Swift and UIKit/SwiftUI",
      "Experience with complex animations",
      "App Store optimization knowledge",
    ],
    skills: ["Swift", "SwiftUI", "UIKit", "ARKit", "Core Data", "Xcode"],
    category: "Tech",
    featured: false,
    experience: "senior",
    workMode: "onsite",
    industry: "Education",
    noticePeriod: "2-months",
    companyRating: 3.5,
    applicantCount: 298,
  },
  {
    title: "SEO Specialist",
    company: "Vivid Agency",
    companySlug: "vivid-agency",
    logo: "https://ui-avatars.com/api/?name=Vivid&background=ec4899&color=fff&bold=true",
    location: "Remote (US)",
    city: "Remote",
    salary: "$60,000 – $78,000",
    salaryMin: 60000,
    salaryMax: 78000,
    type: "remote",
    description:
      "Drive organic growth for agency clients through technical SEO, content strategy, and link building. Report on KPIs monthly and grow client organic traffic by 30%+ year over year.",
    requirements: [
      "2+ years SEO experience",
      "Ahrefs or Semrush proficiency",
      "Technical SEO audit skills",
      "Agency experience a plus",
    ],
    skills: ["SEO", "Ahrefs", "Semrush", "Content Strategy", "Link Building"],
    category: "Marketing",
    featured: false,
    experience: "junior",
    workMode: "remote",
    industry: "Consulting",
    noticePeriod: "15-days",
    companyRating: 4.2,
    applicantCount: 156,
  },
  {
    title: "Android Developer",
    company: "OLA",
    companySlug: "ola",
    logo: "https://ui-avatars.com/api/?name=OLA&background=ffd500&color=1a1a1a&bold=true",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    salary: "₹18 – ₹30 LPA",
    salaryMin: 1800000,
    salaryMax: 3000000,
    type: "full-time",
    description:
      "Build native Android features for OLA's ride-hailing and EV apps used by 200M+ customers. Own the real-time tracking, payments, and driver-matching modules.",
    requirements: [
      "3+ years Android development",
      "Kotlin and Jetpack Compose",
      "Real-time data handling experience",
      "Experience with maps SDKs",
    ],
    skills: ["Kotlin", "Jetpack Compose", "Android SDK", "Google Maps API", "Retrofit"],
    category: "Tech",
    featured: false,
    experience: "mid",
    workMode: "hybrid",
    industry: "E-Commerce",
    noticePeriod: "1-month",
    companyRating: 3.8,
    applicantCount: 342,
  },
  {
    title: "Fresher – Software Engineer Trainee",
    company: "TCS",
    companySlug: "tcs",
    logo: "https://ui-avatars.com/api/?name=TCS&background=0c2d83&color=fff&bold=true",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    salary: "₹3.5 – ₹4.5 LPA",
    salaryMin: 350000,
    salaryMax: 450000,
    type: "full-time",
    description:
      "Start your software engineering career with TCS's industry-renowned ILP (Initial Learning Program). You'll receive 3 months of intensive training in Java, DBMS, and agile practices before joining a live project.",
    requirements: [
      "B.E./B.Tech in CS/IT or related field",
      "60%+ throughout academics (X, XII, Degree)",
      "No active backlogs",
      "Good communication and aptitude",
    ],
    skills: ["Java", "SQL", "Core Java", "DBMS", "Problem Solving"],
    category: "Tech",
    featured: false,
    experience: "fresher",
    workMode: "onsite",
    industry: "IT",
    noticePeriod: "immediate",
    companyRating: 3.7,
    applicantCount: 8420,
  },
];

async function main() {
  console.log("🌱 Starting database seed...");

  // Clear existing seeded data
  await prisma.application.deleteMany({});
  await prisma.savedJob.deleteMany({});
  await prisma.job.deleteMany({ where: { isSeeded: true } });

  // Insert all jobs
  const created = await Promise.all(
    rawJobs.map((job) =>
      prisma.job.create({
        data: {
          ...job,
          isSeeded: true,
        },
      })
    )
  );

  console.log(`✅ Seeded ${created.length} jobs successfully.`);
  console.log(
    "   Companies:",
    [...new Set(rawJobs.map((j) => j.company))].length
  );
  console.log(
    "   Categories:",
    [...new Set(rawJobs.map((j) => j.category))].join(", ")
  );
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
